import { Recipe, FamilyRecipe } from '../types';

export const sampleRecipes: Recipe[] = [
  {
    id: 'sample-1',
    title: "Grandma's Chocolate Chip Cookies",
    description: 'The cookies everyone asks for at every gathering. Crispy edges, chewy center, perfect every time.',
    emoji: '🍪',
    ingredients: [
      '2¼ cups all-purpose flour',
      '1 tsp baking soda',
      '1 tsp salt',
      '1 cup (2 sticks) butter, softened',
      '¾ cup granulated sugar',
      '¾ cup packed brown sugar',
      '2 large eggs',
      '2 tsp vanilla extract',
      '2 cups chocolate chips',
    ],
    instructions: [
      'Preheat oven to 375°F. Line baking sheets with parchment paper.',
      'Whisk together flour, baking soda, and salt in a bowl. Set aside.',
      'Beat butter and both sugars with a mixer until light and fluffy, about 3 minutes.',
      'Add eggs one at a time, beating well after each. Mix in vanilla.',
      'Gradually stir in flour mixture until just combined. Fold in chocolate chips.',
      'Drop rounded tablespoons onto prepared baking sheets, spacing 2 inches apart.',
      'Bake for 9–11 minutes until golden around edges but still soft in center.',
      'Cool on baking sheet for 5 minutes before transferring to a wire rack.',
    ],
    prepTime: '15 min',
    cookTime: '11 min',
    servings: '48 cookies',
    tags: ['dessert', 'baking', 'family-favorite'],
    notes: [
      {
        id: 'n1',
        text: 'Used dark chocolate chips — SO much better 🙌',
        timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
      {
        id: 'n2',
        text: 'Kids helped make these. Double the batch next time!',
        timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
      },
    ],
    savedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    isFavorite: true,
  },
  {
    id: 'sample-2',
    title: 'One-Pan Lemon Garlic Chicken',
    description: 'Weeknight dinner winner. Ready in 30 minutes, minimal cleanup, maximum flavor.',
    emoji: '🍋',
    ingredients: [
      '4 chicken thighs, bone-in skin-on',
      '4 cloves garlic, minced',
      '2 lemons, sliced',
      '2 tbsp olive oil',
      '1 tsp dried thyme',
      '1 tsp dried rosemary',
      'Salt and black pepper to taste',
      'Fresh parsley for garnish',
    ],
    instructions: [
      'Pat chicken dry with paper towels. Season generously with salt and pepper.',
      'Heat olive oil in a large oven-safe skillet over medium-high heat.',
      'Sear chicken skin-side down for 5–6 minutes until golden and crispy.',
      'Flip chicken, add garlic, and cook 1 minute until fragrant.',
      'Add lemon slices around the chicken. Sprinkle thyme and rosemary.',
      'Transfer skillet to 400°F oven. Roast for 20–25 minutes until cooked through.',
      'Let rest 5 minutes. Garnish with fresh parsley and serve with pan juices.',
    ],
    prepTime: '5 min',
    cookTime: '30 min',
    servings: '4 people',
    tags: ['dinner', 'chicken', 'easy', 'weeknight'],
    notes: [
      {
        id: 'n3',
        text: 'Make again! Everyone cleaned their plates.',
        timestamp: new Date(Date.now() - 86400000 * 1).toISOString(),
      },
    ],
    savedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    isFavorite: false,
  },
  {
    id: 'sample-3',
    title: 'Classic Tomato Basil Pasta',
    description: 'Simple, fresh, and ready faster than ordering takeout.',
    emoji: '🍝',
    ingredients: [
      '400g spaghetti or linguine',
      '3 cups cherry tomatoes, halved',
      '4 cloves garlic, thinly sliced',
      '¼ cup extra virgin olive oil',
      'Large handful fresh basil leaves',
      '½ tsp red pepper flakes',
      'Salt and black pepper to taste',
      'Freshly grated Parmesan to serve',
    ],
    instructions: [
      'Cook pasta in well-salted boiling water until al dente. Reserve 1 cup pasta water.',
      'Meanwhile, heat olive oil in a large pan over medium heat.',
      'Add garlic and red pepper flakes; cook 1–2 minutes until softened but not browned.',
      'Add cherry tomatoes, season with salt. Cook 8–10 minutes until they burst and form a sauce.',
      'Add drained pasta to the pan. Toss with pasta water to create a silky sauce.',
      'Remove from heat. Tear basil over the top. Adjust seasoning.',
      'Serve immediately topped with freshly grated Parmesan.',
    ],
    prepTime: '5 min',
    cookTime: '20 min',
    servings: '4 people',
    tags: ['pasta', 'vegetarian', 'quick', 'dinner'],
    notes: [],
    savedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    isFavorite: false,
  },
  {
    id: 'sample-4',
    title: 'Banana Oat Breakfast Pancakes',
    description: 'No flour, no added sugar. 2-ingredient base. Kids love them every single time.',
    emoji: '🥞',
    ingredients: [
      '2 ripe bananas',
      '2 large eggs',
      '½ cup rolled oats',
      '1 tsp vanilla extract',
      'Pinch of cinnamon',
      'Coconut oil for cooking',
      'Fresh berries to serve',
      'Maple syrup to serve',
    ],
    instructions: [
      'Mash bananas in a bowl until smooth.',
      'Beat in eggs, oats, vanilla, and cinnamon. Let batter rest 2 minutes.',
      'Heat coconut oil in a non-stick pan over medium-low heat.',
      'Pour small amounts of batter (2 tbsp each) for silver-dollar pancakes.',
      'Cook 2–3 minutes until bubbles form on surface and edges look set.',
      'Flip carefully and cook another 1–2 minutes.',
      'Serve with fresh berries and a drizzle of maple syrup.',
    ],
    prepTime: '5 min',
    cookTime: '15 min',
    servings: '2 people (8 pancakes)',
    tags: ['breakfast', 'healthy', 'kids'],
    notes: [
      {
        id: 'n4',
        text: 'Used less sugar — perfect. Kids devoured them.',
        timestamp: new Date(Date.now() - 86400000 * 14).toISOString(),
      },
    ],
    savedAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    isFavorite: true,
  },
  {
    id: 'sample-5',
    title: 'Slow Cooker Beef Stew',
    description: 'Set it and forget it. Come home to a house that smells like heaven.',
    emoji: '🥘',
    ingredients: [
      '2 lbs beef chuck, cut into 1½-inch chunks',
      '4 carrots, cut into coins',
      '4 Yukon gold potatoes, cubed',
      '1 onion, diced',
      '3 cloves garlic, minced',
      '2 cups beef broth',
      '2 tbsp tomato paste',
      '1 tbsp Worcestershire sauce',
      '2 tbsp all-purpose flour',
      '1 tsp dried thyme',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Toss beef with flour, salt, and pepper. Brown in a hot pan with oil — optional but adds depth.',
      'Add beef to slow cooker with all vegetables.',
      'Whisk together broth, tomato paste, Worcestershire, and thyme. Pour over everything.',
      'Cook on LOW for 8 hours or HIGH for 4–5 hours until beef is fall-apart tender.',
      'Taste and adjust salt. Serve with crusty bread to soak up the broth.',
    ],
    prepTime: '20 min',
    cookTime: '8 hrs',
    servings: '6 people',
    tags: ['dinner', 'slow-cooker', 'comfort-food', 'meal-prep'],
    notes: [],
    savedAt: new Date(Date.now() - 86400000 * 21).toISOString(),
    isFavorite: false,
  },
];

export const sampleFamilyRecipes: FamilyRecipe[] = [
  {
    id: 'family-1',
    title: "Nana's Sunday Pot Roast",
    contributor: 'Margaret Kowalski',
    relationship: 'Grandmother',
    familyStory:
      "Made every Sunday for 40 years. The whole family would drive over just for this. Nana always said the secret was patience — never rush a pot roast.",
    decade: '1970s',
    ingredients: [
      '3–4 lb beef chuck roast',
      '4 russet potatoes, quartered',
      '4 carrots, halved',
      '2 stalks celery, chopped',
      '1 large onion, quartered',
      '2 cups beef broth',
      '1 packet onion soup mix',
      'Salt, pepper, garlic powder',
    ],
    instructions: [
      'Season roast generously on all sides.',
      'Place vegetables in slow cooker, then roast on top.',
      'Mix broth with onion soup mix and pour over everything.',
      'Cook on LOW for 8–10 hours.',
      'Shred with forks and serve with the vegetables.',
    ],
    notes: [],
    savedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
];
